### ISSUE TITLE
User's `layer.xml` combination with `generated-layer.xml`.

### ISSUE THREAD

**Issue by marat-gainullin** [radimk/gradle-nbm-plugin#13] opened 2016-12-10 08:49 UTC
There are lots of `layer.xml` settings, that can not be replaced with annotations. So it is highly desireable to have an option to combine `generated-layer.xml` with some user's `layer.xml` like it happens with `manifest.mf`

**Comment by radimk** [comment] 2016-12-10 10:33
I believe this is duplicate of #8

As far as I can tell it enough to add  `OpenIDE-Module-Layer: path/to/your/layer.xml` to manifest file. Module JAR will then contain both your layer and generated one. NetBeans is probably doing a merge in the runtime when it looks for an entry with pre-defined name `META-INF/generated-layer.xml` and an entry declared in your manifest.

It can be useful to add this into a sample to let people know this is working. Would you mind to create a patch with a reasonable example?

**Comment by marat-gainullin** [comment] 2016-12-13 06:47
If pull request will be merged, this issue should be closed.

**Comment by kelemen** [comment] 2016-12-13 09:22
There is an option and I'm relying on it, so it works. You just have to specify your custom layer.xml in the manifest and it will get merged with the generated one.

**Comment by marat-gainullin** [comment] 2016-12-14 14:52
Yes. It works. But the PR is about sample project. It is not about `gradle-nbm-plugin` code itself.
As radmik said "It can be useful to add this into a sample to let people know this is working".

**Comment by radimk** [comment] 2016-12-16 20:32
The other PR is integrated so I'm closing this one as we discussed.

**Closed** 2016-12-16 21:06 UTC
